# Generated by Django 4.2.7 on 2023-11-19 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_goods_delete_post_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товари'},
        ),
    ]
